#!/data/data/com.termux/files/usr/bin/bash
# termux-state.sh — Detect and persist Termux environment state
# Survives AI context compaction by storing state on disk
# Usage: source termux-state.sh  OR  eval "$(termux-state.sh)"

STATE_FILE="${HOME}/.termux-skill-state"

detect_termux_env() {
  if command -v termux-battery-status &>/dev/null && [ -n "${TERMUX_VERSION-}" ]; then
    ENV="native"
    PREFIX=""
    SSH_HOST=""
    SSH_PORT=""
  elif [ -d /data/data/com.termux/files/usr/bin ] && ls /data/data/com.termux/files/usr/bin/termux-* &>/dev/null 2>&1; then
    ENV="proot"
    PREFIX="/data/data/com.termux/files/usr/bin"
    SSH_HOST=""
    SSH_PORT=""
  else
    ENV="ssh"
    PREFIX="ssh"
    SSH_HOST="${TERMUX_SSH_HOST:-localhost}"
    SSH_PORT="${TERMUX_SSH_PORT:-8022}"
  fi
}

save_state() {
  cat > "$STATE_FILE" << EOF
# Auto-generated by termux-skill — do not edit manually
# Regenerate: source termux-state.sh
TERMUX_ENV=$ENV
TERMUX_PREFIX=$PREFIX
TERMUX_SSH_HOST=$SSH_HOST
TERMUX_SSH_PORT=$SSH_PORT
TERMUX_DETECTED_AT=$(date -Iseconds)
EOF
  echo "State saved: ENV=$ENV PREFIX=${PREFIX:-<native>}"
}

load_state() {
  if [ -f "$STATE_FILE" ]; then
    source "$STATE_FILE"
    return 0
  fi
  return 1
}

termux_exec() {
  local cmd=$1; shift
  if [ "$TERMUX_ENV" = "native" ] || command -v "$cmd" &>/dev/null 2>&1; then
    "$cmd" "$@"
  elif [ "$TERMUX_ENV" = "proot" ] && [ -x "${TERMUX_PREFIX}/${cmd}" ]; then
    "${TERMUX_PREFIX}/${cmd}" "$@"
  elif [ "$TERMUX_ENV" = "ssh" ]; then
    ssh -p "$TERMUX_SSH_PORT" "$TERMUX_SSH_HOST" "$cmd $*"
  else
    # Fallback: try direct, then proot path, then SSH
    if command -v "$cmd" &>/dev/null 2>&1; then
      "$cmd" "$@"
    elif [ -x "/data/data/com.termux/files/usr/bin/$cmd" ]; then
      "/data/data/com.termux/files/usr/bin/$cmd" "$@"
    else
      echo "ERROR: Cannot find $cmd. Run 'source termux-state.sh' to re-detect environment." >&2
      return 1
    fi
  fi
}

# List all available termux-* commands on this device
termux_list() {
  local bin_dir="${TERMUX_PREFIX:+$TERMUX_PREFIX/}"
  local cmds=()

  # Native or proot: scan filesystem
  if [ "$TERMUX_ENV" != "ssh" ]; then
    for f in "${bin_dir}"termux-*; do
      [ -x "$f" ] && cmds+=("$(basename "$f")")
    done
  else
    # SSH: ask remote
    cmds=($(ssh -p "$TERMUX_SSH_PORT" "$TERMUX_SSH_HOST" 'compgen -c termux-' 2>/dev/null))
  fi

  if [ ${#cmds[@]} -eq 0 ]; then
    echo "No termux-* commands found." >&2
    return 1
  fi

  printf '%s\n' "${cmds[@]}" | sort
}

# Quick help for a termux command
termux_help() {
  local cmd=$1
  if [ -z "$cmd" ]; then
    echo "Usage: termux_help <command>" >&2
    echo "Example: termux_help termux-notification" >&2
    return 1
  fi

  # Try --help flag
  local output
  output=$(termux_exec "$cmd" --help 2>&1)
  if [ $? -eq 0 ] && [ -n "$output" ]; then
    echo "$output"
  else
    # Fallback: show man page or usage hint
    echo "No --help available for $cmd"
    echo "Try: termux_exec $cmd (with appropriate args)"
  fi
}

# Auto-detect if not loaded from source (i.e., executed directly)
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  detect_termux_env
  save_state
else
  # Sourced — try load first, detect if missing
  if ! load_state; then
    detect_termux_env
    save_state
  fi
fi

# Sync PREFIX → TERMUX_PREFIX for consistency
: "${TERMUX_PREFIX:=$PREFIX}"

# Export everything for subshells
export -f termux_exec termux_list termux_help 2>/dev/null
export TERMUX_ENV TERMUX_PREFIX SSH_HOST SSH_PORT
