#!/data/data/com.termux/files/usr/bin/bash
# termux-state.sh — Detect and persist Termux environment state
# Survives AI context compaction by storing state on disk
# Usage: source termux-state.sh  OR  eval "$(termux-state.sh)"

STATE_FILE="${HOME}/.termux-skill-state"

detect_termux_env() {
  if command -v termux-battery-status &>/dev/null && [ -n "${TERMUX_VERSION-}" ]; then
    ENV="native"
    PREFIX=""
    SSH_HOST=""
    SSH_PORT=""
  elif [ -d /data/data/com.termux/files/usr/bin ] && ls /data/data/com.termux/files/usr/bin/termux-* &>/dev/null 2>&1; then
    ENV="proot"
    PREFIX="/data/data/com.termux/files/usr/bin"
    SSH_HOST=""
    SSH_PORT=""
  else
    ENV="ssh"
    PREFIX="ssh"
    SSH_HOST="${TERMUX_SSH_HOST:-localhost}"
    SSH_PORT="${TERMUX_SSH_PORT:-8022}"
  fi
}

save_state() {
  cat > "$STATE_FILE" << EOF
# Auto-generated by termux-skill — do not edit manually
# Regenerate: source termux-state.sh
TERMUX_ENV=$ENV
TERMUX_PREFIX=$PREFIX
TERMUX_SSH_HOST=$SSH_HOST
TERMUX_SSH_PORT=$SSH_PORT
TERMUX_DETECTED_AT=$(date -Iseconds)
EOF
  echo "State saved: ENV=$ENV PREFIX=${PREFIX:-<native>}"
}

load_state() {
  if [ -f "$STATE_FILE" ]; then
    source "$STATE_FILE"
    return 0
  fi
  return 1
}

termux_exec() {
  local cmd=$1; shift
  if [ "$TERMUX_ENV" = "native" ] || command -v "$cmd" &>/dev/null 2>&1; then
    "$cmd" "$@"
  elif [ "$TERMUX_ENV" = "proot" ] && [ -x "${TERMUX_PREFIX}/${cmd}" ]; then
    "${TERMUX_PREFIX}/${cmd}" "$@"
  elif [ "$TERMUX_ENV" = "ssh" ]; then
    ssh -p "$TERMUX_SSH_PORT" "$TERMUX_SSH_HOST" "$cmd $*"
  else
    # Fallback: try direct, then proot path, then SSH
    if command -v "$cmd" &>/dev/null 2>&1; then
      "$cmd" "$@"
    elif [ -x "/data/data/com.termux/files/usr/bin/$cmd" ]; then
      "/data/data/com.termux/files/usr/bin/$cmd" "$@"
    else
      echo "ERROR: Cannot find $cmd. Run 'source termux-state.sh' to re-detect environment." >&2
      return 1
    fi
  fi
}

# Auto-detect if not loaded from source (i.e., executed directly)
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
  detect_termux_env
  save_state
  # Also export for subshells
  export TERMUX_ENV PREFIX SSH_HOST SSH_PORT
else
  # Sourced — try load first, detect if missing
  if ! load_state; then
    detect_termux_env
    save_state
  fi
  export TERMUX_ENV PREFIX SSH_HOST SSH_PORT
fi
